import imgFirstSectionNovels1 from './1.webp';
import imgFirstSectionNovels2 from './2.webp';
import imgFirstSectionNovels3 from './3.webp';
import imgFirstSectionNovels4 from './4.webp';
import imgFirstSectionNovels5 from './5.webp';
import imgFirstSectionNovels6 from './6.webp';
import imgFirstSectionNovels7 from './7.webp';
import imgFirstSectionNovels8 from './8.webp';
import imgFirstSectionNovels9 from './9.webp';
import imgFirstSectionNovels10 from './10.webp';
import imgFirstSectionNovels11 from './11.webp';
import imgFirstSectionNovels12 from './12.webp';
import imgFirstSectionNovels13 from './13.webp';
import imgFirstSectionNovels14 from './14.webp';
import imgFirstSectionNovels15 from './15.webp';
import imgFirstSectionNovels16 from './16.webp';
import imgFirstSectionNovels17 from './17.webp';
import imgFirstSectionNovels18 from './18.webp';

export const imageFirstSectionNovels1: string = imgFirstSectionNovels1;
export const imageFirstSectionNovels2: string = imgFirstSectionNovels2;
export const imageFirstSectionNovels3: string = imgFirstSectionNovels3;
export const imageFirstSectionNovels4: string = imgFirstSectionNovels4;
export const imageFirstSectionNovels5: string = imgFirstSectionNovels5;
export const imageFirstSectionNovels6: string = imgFirstSectionNovels6;
export const imageFirstSectionNovels7: string = imgFirstSectionNovels7;
export const imageFirstSectionNovels8: string = imgFirstSectionNovels8;
export const imageFirstSectionNovels9: string = imgFirstSectionNovels9;
export const imageFirstSectionNovels10: string = imgFirstSectionNovels10;
export const imageFirstSectionNovels11: string = imgFirstSectionNovels11;
export const imageFirstSectionNovels12: string = imgFirstSectionNovels12;
export const imageFirstSectionNovels13: string = imgFirstSectionNovels13;
export const imageFirstSectionNovels14: string = imgFirstSectionNovels14;
export const imageFirstSectionNovels15: string = imgFirstSectionNovels15;
export const imageFirstSectionNovels16: string = imgFirstSectionNovels16;
export const imageFirstSectionNovels17: string = imgFirstSectionNovels17;
export const imageFirstSectionNovels18: string = imgFirstSectionNovels18;
