import imgFirstSectionBooks1 from './1.webp';
import imgFirstSectionBooks2 from './2.webp';
import imgFirstSectionBooks3 from './3.webp';
import imgFirstSectionBooks4 from './4.webp';
import imgFirstSectionBooks5 from './5.webp';
import imgFirstSectionBooks6 from './6.webp';
import imgFirstSectionBooks7 from './7.webp';
import imgFirstSectionBooks8 from './8.webp';
import imgFirstSectionBooks9 from './9.webp';
import imgFirstSectionBooks10 from './10.webp';
import imgFirstSectionBooks11 from './11.webp';
import imgFirstSectionBooks12 from './12.webp';
import imgFirstSectionBooks13 from './13.webp';
import imgFirstSectionBooks14 from './14.webp';
import imgFirstSectionBooks15 from './15.webp';
import imgFirstSectionBooks16 from './16.webp';
import imgFirstSectionBooks17 from './17.webp';
import imgFirstSectionBooks18 from './18.webp';

export const imageFirstSectionBooks1: string = imgFirstSectionBooks1;
export const imageFirstSectionBooks2: string = imgFirstSectionBooks2;
export const imageFirstSectionBooks3: string = imgFirstSectionBooks3;
export const imageFirstSectionBooks4: string = imgFirstSectionBooks4;
export const imageFirstSectionBooks5: string = imgFirstSectionBooks5;
export const imageFirstSectionBooks6: string = imgFirstSectionBooks6;
export const imageFirstSectionBooks7: string = imgFirstSectionBooks7;
export const imageFirstSectionBooks8: string = imgFirstSectionBooks8;
export const imageFirstSectionBooks9: string = imgFirstSectionBooks9;
export const imageFirstSectionBooks10: string = imgFirstSectionBooks10;
export const imageFirstSectionBooks11: string = imgFirstSectionBooks11;
export const imageFirstSectionBooks12: string = imgFirstSectionBooks12;
export const imageFirstSectionBooks13: string = imgFirstSectionBooks13;
export const imageFirstSectionBooks14: string = imgFirstSectionBooks14;
export const imageFirstSectionBooks15: string = imgFirstSectionBooks15;
export const imageFirstSectionBooks16: string = imgFirstSectionBooks16;
export const imageFirstSectionBooks17: string = imgFirstSectionBooks17;
export const imageFirstSectionBooks18: string = imgFirstSectionBooks18;
